continents = {
'Turkey':"Asia",
'Afghanistan':"Asia",
'Burundi':"Africa",
'Pakistan':"Asia",
'Algeria':"Africa",
'Jordan':"Asia",
'Iraq':'Asia',
'Somalia':'Africa',
'Burkina Faso':'Africa',
'Egypt':'Africa',
'Yemen':'Asia',
'Central African Republic':'Africa',
'Philippines':'Asia',
'Nigeria':'Africa',
'Chile':'South America',
'Syria':'Asia',
'Israel':'Asia',
'Sweden':'Europe',
'India':'Asia',
'Saudi Arabia':'Asia',
'East Jerusalem, Israel':'Asia',
'Colombia':'South America',
'Greece':'Europe',
'Ethiopia':'Africa',
"al-Fari'ah, West Bank":'Asia',
'Paraguay':'South America',
'Mali':'Africa',
'United Kingdom':'Europe',
'Cameroon':'Africa',
'Niger':'Africa',
'Mexico':'South America',
'Ukraine':'Europe',
'Libya':'Africa',
'Lebanon':'Asia',
'Kenya':'Africa',
'Bahrain':'Asia',
'Bangladesh':'Asia',
'Russia':'Asia',
'Canada':'North America',
'South Sudan':'Africa',
'United States':'North America',
'Azerbaijan':'Asia',
'France':'Europe',
'China':'Asia',
'Peru':'South America',
'Guatemala':"Middle America",
'Indonesia':"Asia",
'Thailand':"Asia",
'Ivory Coast':"Africa",
'Tunisia':"Africa",
'Uganda':"Africa",
'Democratic Republic of the Congo':"Africa",
'Belgium':"Europe",
'Australia':"Australia",
'Norway':"Europe",
'Kalandia, West Bank':"Asia",
'Iran':"Asia",
'Chad':"Africa",
'Italy':"Europe",
'Afganistan':"Asia" }